AWSTemplateFormatVersion: 2010-09-09
Description: Template para Criacao de um Cluster Kubernetes

Parameters:
  FaixaIPdoVPC:
    Description: Faixa IP a ser Utilizada no VPC
    Type: String
    Default: 10.240.0.0/16
  FaixaIPdaSubRede:
    Description: Faixa IP a ser utiliza na SubRede
    Type: String
    Default: 10.240.0.0/24
  ZonaSubRede:
    Description: Zona da SubRede 
    Type: Number
    Default: 1
  KeyName:
    Description: Nome do par de Chaves
    Type: AWS::EC2::KeyPair::KeyName
    Default: saturn
  InstanceType:
    Description: Tipo de Instancia
    Type: String
    Default: t3.medium
Mappings:
  RegionMap:
    us-east-1:
      "Ubuntu2004": "ami-0885b1f6bd170450c"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: FaixaIPdoVPC
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Kubernetes
  SubRede:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: [ 
          Ref: ZonaSubRede, 
          Fn::GetAZs: '' 
        ]
      VpcId:
        Ref: VPC
      CidrBlock: 
        Ref:
          FaixaIPdaSubRede
      Tags:
        - Key: Name
          Value: Kubernetes
  RoteadorInternet:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Kubernetes
  LigacaoRoteadorVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Ref: VPC
      InternetGatewayId: 
        Ref: RoteadorInternet 
  IPElastico:
    Type: AWS::EC2::EIP
    DependsOn: LigacaoRoteadorVPC
    Properties:
      Domain: vpc
  NAT:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt: [
          IPElastico,
          AllocationId
        ]
      SubnetId:
        Ref: SubRede
      Tags:
        - Key: Name 
          Value: Kubernetes 
  TabelaRoteamentoRede:
    Type: AWS::EC2::RouteTable 
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name 
          Value: Kubernetes
  RotaRedePadrao:
    Type: AWS::EC2::Route 
    Properties: 
      GatewayId: 
        Ref: RoteadorInternet 
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: 
        Ref: TabelaRoteamentoRede

  RotaRedePod0:
    Type: AWS::EC2::Route 
    Properties:
      DestinationCidrBlock: 192.168.0.0/24
      InstanceId:
        Ref: worker0
      RouteTableId: 
        Ref: TabelaRoteamentoRede

  RotaRedePod1:
    Type: AWS::EC2::Route 
    Properties:
      DestinationCidrBlock: 192.168.1.0/24
      InstanceId:
        Ref: worker1
      RouteTableId: 
        Ref: TabelaRoteamentoRede

  RotaRedePod2:
    Type: AWS::EC2::Route 
    Properties:
      DestinationCidrBlock: 192.168.2.0/24
      InstanceId:
        Ref: worker2
      RouteTableId: 
        Ref: TabelaRoteamentoRede

  AssociacaoTabelaSubRede:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SubRede
      RouteTableId:
        Ref: TabelaRoteamentoRede
  GrupoDeSeguranca:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Kubernetes
      GroupDescription:  Grupo de Seguranca do Cluster Kubernetes
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp 
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 6443
          IpProtocol: tcp 
          ToPort: 6443
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp 
          ToPort: 443
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: icmp 
          ToPort: -1
        - CidrIp: 192.168.0.0/16
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: Kubernetes
  RegraEntradaGrupoDeSeguranca:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: GrupoDeSeguranca
    Properties:
      GroupId:
        Ref: GrupoDeSeguranca
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId:
        Ref: GrupoDeSeguranca

  BalanceadorDeCarga:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer 
    Properties:
      Name: "Kubernetes"
      Type: "network"
      Subnets:
        - Ref: SubRede 
      Scheme: "internet-facing"
  
  GrupoAlvo:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup 
    Properties:
      Name: "Kubernetes"
      Protocol: "TCP"
      Port: 6443
      VpcId:
        Ref: VPC
      TargetType: "ip" 
      Targets:
        - Id: 10.240.0.10
        - Id: 10.240.0.11
        - Id: 10.240.0.12

  Ouvinte:
    Type: AWS::ElasticLoadBalancingV2::Listener 
    Properties:
      LoadBalancerArn:
        Ref: BalanceadorDeCarga
      Protocol: "TCP" 
      Port: 443
      DefaultActions:
        - Type: "forward"
          TargetGroupArn:
            Ref: GrupoAlvo 

  controller0:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - Ref: 'AWS::Region'
          - Ubuntu2004
      InstanceType:
        Ref: InstanceType  
      Tags:
        - Key: Name
          Value: controller-0
      NetworkInterfaces:
        - PrivateIpAddress: 10.240.0.10
          AssociatePublicIpAddress: true 
          DeleteOnTermination: true 
          SubnetId:
            Ref: SubRede 
          DeviceIndex: 0
          GroupSet:
            - Ref: GrupoDeSeguranca
      SourceDestCheck: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 40
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash -ex
            
            # Configura o hostname
            hostname controller-0
            echo "controller-0" > /etc/hostname

            # Configura a resolução de nomes
            cat>> /etc/hosts <<EOF
            10.240.0.10 controller-0  
            10.240.0.11 controller-1 
            10.240.0.12 controller-2 
            10.240.0.20 worker-0 
            10.240.0.21 worker-1 
            10.240.0.22 worker-2 
            EOF

  controller1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - Ref: 'AWS::Region'
          - Ubuntu2004
      InstanceType:
        Ref: InstanceType  
      Tags:
        - Key: Name
          Value: controller-1
      NetworkInterfaces:
        - PrivateIpAddress: 10.240.0.11
          AssociatePublicIpAddress: true 
          DeleteOnTermination: true 
          SubnetId:
            Ref: SubRede 
          DeviceIndex: 0
          GroupSet:
            - Ref: GrupoDeSeguranca
      SourceDestCheck: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 40
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash -ex
            
            # Configura o hostname
            hostname controller-1
            echo "controller-1" > /etc/hostname

            # Configura a resolução de nomes
            cat>> /etc/hosts <<EOF
            10.240.0.10 controller-0  
            10.240.0.11 controller-1 
            10.240.0.12 controller-2 
            10.240.0.20 worker-0 
            10.240.0.21 worker-1 
            10.240.0.22 worker-2 
            EOF

  controller2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - Ref: 'AWS::Region'
          - Ubuntu2004
      InstanceType:
        Ref: InstanceType  
      Tags:
        - Key: Name
          Value: controller-2
      NetworkInterfaces:
        - PrivateIpAddress: 10.240.0.12
          AssociatePublicIpAddress: true 
          DeleteOnTermination: true 
          SubnetId:
            Ref: SubRede 
          DeviceIndex: 0
          GroupSet:
            - Ref: GrupoDeSeguranca
      SourceDestCheck: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 40      
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash -ex
            
            # Configura o hostname
            hostname controller-2
            echo "controller-2" > /etc/hostname

            # Configura a resolução de nomes
            cat>> /etc/hosts <<EOF
            10.240.0.10 controller-0  
            10.240.0.11 controller-1 
            10.240.0.12 controller-2 
            10.240.0.20 worker-0 
            10.240.0.21 worker-1 
            10.240.0.22 worker-2 
            EOF

  worker0:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - Ref: 'AWS::Region'
          - Ubuntu2004
      InstanceType:
        Ref: InstanceType  
      Tags:
        - Key: Name
          Value: worker-0
      NetworkInterfaces:
        - PrivateIpAddress: 10.240.0.20
          AssociatePublicIpAddress: true 
          DeleteOnTermination: true 
          SubnetId:
            Ref: SubRede 
          DeviceIndex: 0
          GroupSet:
            - Ref: GrupoDeSeguranca
      SourceDestCheck: false
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash -ex
            
            # Configura o hostname
            hostname worker-0
            echo "worker-0" > /etc/hostname

            # Configura a resolução de nomes
            cat>> /etc/hosts <<EOF
            10.240.0.10 controller-0  
            10.240.0.11 controller-1 
            10.240.0.12 controller-2 
            10.240.0.20 worker-0 
            10.240.0.21 worker-1 
            10.240.0.22 worker-2 
            EOF

  worker1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - Ref: 'AWS::Region'
          - Ubuntu2004
      InstanceType:
        Ref: InstanceType  
      Tags:
        - Key: Name
          Value: worker-1
      NetworkInterfaces:
        - PrivateIpAddress: 10.240.0.21
          AssociatePublicIpAddress: true 
          DeleteOnTermination: true 
          SubnetId:
            Ref: SubRede 
          DeviceIndex: 0
          GroupSet:
            - Ref: GrupoDeSeguranca
      SourceDestCheck: false
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash -ex
            
            # Configura o hostname
            hostname worker-1
            echo "worker-1" > /etc/hostname

            # Configura a resolução de nomes
            cat>> /etc/hosts <<EOF
            10.240.0.10 controller-0  
            10.240.0.11 controller-1 
            10.240.0.12 controller-2 
            10.240.0.20 worker-0 
            10.240.0.21 worker-1 
            10.240.0.22 worker-2 
            EOF

  worker2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - Ref: 'AWS::Region'
          - Ubuntu2004
      InstanceType:
        Ref: InstanceType  
      Tags:
        - Key: Name
          Value: worker-2
      NetworkInterfaces:
        - PrivateIpAddress: 10.240.0.22
          AssociatePublicIpAddress: true 
          DeleteOnTermination: true 
          SubnetId:
            Ref: SubRede 
          DeviceIndex: 0
          GroupSet:
            - Ref: GrupoDeSeguranca
      SourceDestCheck: false
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash -ex
            
            # Configura o hostname
            hostname worker-2
            echo "worker-2" > /etc/hostname

            # Configura a resolução de nomes
            cat>> /etc/hosts <<EOF
            10.240.0.10 controller-0  
            10.240.0.11 controller-1 
            10.240.0.12 controller-2 
            10.240.0.20 worker-0 
            10.240.0.21 worker-1 
            10.240.0.22 worker-2 
            EOF


Outputs:
  EnderecoPublicoKubernetes:
    Value:
      Fn::GetAtt: [
        BalanceadorDeCarga,
        DNSName
      ]

  EnderecoPublicoController0:
    Value:
      Fn::GetAtt: [
        controller0,
        PublicIp
      ]
  EnderecoPrivadoController0:
    Value:
      Fn::GetAtt: [
        controller0,
        PrivateIp
      ]
  EnderecoPublicoController1:
    Value:
      Fn::GetAtt: [
        controller1,
        PublicIp
      ]
  EnderecoPrivadoController1:
    Value:
      Fn::GetAtt: [
        controller1,
        PrivateIp
      ]
  EnderecoPublicoController2:
    Value:
      Fn::GetAtt: [
        controller2,
        PublicIp
      ]
  EnderecoPrivadoController2:
    Value:
      Fn::GetAtt: [
        controller2,
        PrivateIp
      ]
  EnderecoPublicoWorker0:
    Value:
      Fn::GetAtt: [
        worker0,
        PublicIp
      ]
  EnderecoPrivadoWorker0:
    Value:
      Fn::GetAtt: [
        worker0,
        PrivateIp
      ]
  EnderecoPublicoWorker1:
    Value:
      Fn::GetAtt: [
        worker1,
        PublicIp
      ]
  EnderecoPrivadoWorker1:
    Value:
      Fn::GetAtt: [
        worker1,
        PrivateIp
      ]
  EnderecoPublicoWorker2:
    Value:
      Fn::GetAtt: [
        worker2,
        PublicIp
      ]
  EnderecoPrivadoWorker2:
    Value:
      Fn::GetAtt: [
        worker2,
        PrivateIp
      ]
        
           
